CheckinV02/Controllers/InviteeController.cs
using CheckinV02.BL;
using CheckinV02.Common;
using CheckinV02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CheckinV02.Controllers
{
    public class InviteeController : Controller
    {
        ICurrUserBL CurrentUser;
        IEventBL EventBL;
        IUserBL UserBL;
        public InviteeController(ICurrUserBL currentUser, IEventBL eventBL, IUserBL userBL)
        {
            this.CurrentUser = currentUser;
            this.EventBL = eventBL;
            this.UserBL = userBL;
        }
        public ActionResult Index()
        {
            var currUser = CurrentUser.GetCurrentUser();
            if(!currUser.HasRole(Permission.Admin.GetHashCode(),
                                Permission.InviteeManager.GetHashCode(),
                                Permission.Manager.GetHashCode() ) )
            {
                return View("~/Views/Common/NotPermitted.cshtml");
            }
            var model = new InviteeIndexModel();

            // Lấy thông tin sự kiện mặc định
            model.DefaultEvent = EventBL.GetDefault();
            // Lấy danh sách các CSKH có tài khoản trên hệ thống
            model.LstAssignTo = UserBL.GetByRole(Permission.InviteeManager.GetHashCode());
            // Lấy ra danh sách sự kiện
            model.LstEvent = EventBL.GetActiveAndOrderedCreatedDate();
            // Kiểm tra xem người dùng có quyền xuất excel hay không
            if(currUser.HasRole(Permission.Admin.GetHashCode(),
                                Permission.Manager.GetHashCode()))
            {
                model.IsExportExcelPermission = true;
            }

            return View(model);
        }
    }
}

CheckinV02/Views/Invitee/Index.cshtml
@using CheckinV02.Models
@model InviteeIndexModel
@{
    Layout = null;
}
<h1 style="padding-left: 15px;">
    Quản lý khách mời
</h1>
@using (Html.BeginForm("ExportExcel", "Invitee", FormMethod.Post, new { id = "InviteeForm", target = "_blank" }))
{
    <div class="panel panel-search" id="frmSearchRegisteredInvitee">
        <div class="panel-heading"><i class="icon-cogs"></i> &nbsp; Tìm kiếm thông tin khách mời</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="input-group">
                        <textarea name="TextSearch" rows="5" cols="5" class="form-control" id="txtSearchText" placeholder="Tìm kiếm theo họ tên, email,điện thoại ... "></textarea>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="input-group">
                                <select name="EventId" id="selEvent" class="form-control" title="Danh sách các sự kiện diễn ra">
                                    @foreach (var e in Model.LstEvent)
                                    {
                                        if (e.Id == Model.DefaultEvent.Id)
                                        {
                                            <option selected="selected" value="@(e.Id)">@e.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@(e.Id)">@e.Name</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <select id="dllSessions" class="form-control">
                                    <option value="0">--Chọn phiên --</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="input-group">
                                <select name="InviteeResponseStatus" id="selIsCheckIn" class="form-control" title="Thông tin khách đã check in hay chưa">
                                    <option value="">--Tất cả trạng thái--</option>
                                    <option value="1">Xác nhận lần 1</option>
                                    <option value="2">Xác nhận lần 2</option>
                                    <option value="3">Chưa gọi</option>
                                    <option value="4">Gọi lại sau</option>
                                    <option value="5">Không nghe máy</option>
                                    <option value="6">Đã gọi</option>
                                    <option value="7">Số máy sai</option>
                                    <option value="8">Đang xem xét</option>
                                    <option value="9">Không tham gia</option>
                                    <option value="10">Đã gửi vé </option>
                                    <option value="11">Gửi lại vé </option>
                                    <option value="12">Không mời </option>
                                    <option value="13">Trưởng phòng duyệt </option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="input-group">
                                <select name="SourceId" id="selCustomerType" class="form-control" title="Nguồn khách mời">
                                    <option value="0">- Nguồn khách mời -</option>
                                    <option value="1">BCRM</option>
                                    <option value="2">Landingpage</option>
                                </select>
                            </div>
                        </div>

                    </div>
                    <div class="row" style="margin-top:3px;">
                        <div class="col-md-2">
                            <div class="input-group">
                                <input type="number" name="InviteeCode" id="txtInviteeCode" placeholder="- Mã số -" class="form-control phone-search" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="input-group">
                                <input type="text" name="Code" id="txtCode" placeholder="- Mã vé -" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group date">
                                <input type="text" id="txtStartRegisterDate" value="" placeholder="-- KH bắt đầu đ/kí từ--" class="form-control date">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group date">
                                <input type="text" id="txtEndRegisterDate" value="" placeholder="--  Đến hết ngày đ/kí--" class="form-control date">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="input-group">
                                <select name="AssignTo" id="selAssignTo" class="form-control" title="Giao khách hàng cho">
                                    <option value="">-Giao cho-</option>
                                    @foreach (var assignTo in Model.LstAssignTo)
                                    {
                                        <option value="@assignTo.UserName">@assignTo.UserName</option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-top:3px;">
                        <div class="col-md-4">
                            <div class="input-group">
                                <input type="text" name="IntroduceUser" id="txtIntroduceUser" placeholder="- Nhân viên mời -" class="form-control " />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <select name="FilterAssignTo" id="selFilterAssignTo" class="form-control select" title="Lựa chọn thông tin khách hàng được giao">
                                    <option value="0">- Lựa chọn thông tin khách hàng được giao -</option>
                                    <option value="1">Chưa giao cho ai </option>
                                    <option value="2">Chưa giao cho Sale</option>
                                    <option value="3">Chưa giao cho CSKH</option>
                                    <option value="4">Đã giao cho Sale</option>
                                    <option value="5">Đã giao cho CSKH</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div style="width: 100%;margin-top:3px; margin-bottom: 3px;">
                <button id="btnSearch" class="btn btn-success" type="button">
                    <i class="icon-search"></i>
                    &nbsp;Tìm kiếm
                </button>
                @if (Model.IsExportExcelPermission)
                {
                    <button id="btnExport" class="btn btn-success" type="button">
                        <i class="icon-refresh"></i>&nbsp;Xuất Excel
                    </button>
                }
                <button id="btnAddInvitee" class="btn btn-success" type="button">
                    <i class="icon-plus"></i>
                    &nbsp;Thêm Khách mời
                </button>
                <input type="hidden" id="hdfSearchStartDate" name="StartDate" />
                <input type="hidden" id="hdfSearchEndDate" name="EndDate" />
            </div>
        </div>
    </div>
}

<script lang="en" type="text/javascript">
    invitee_index.init();
</script>