CheckinV02/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CheckinV02.Models
{
    public class UserViewModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Role { get; set; }
        public int Status { get; set; }
        public DateTime? LockedStartDate { get; set; }
        public int LockTime { get; set; }
        public string LockTimeHtml { 
            get{
                if(LockTime >0)
                {
                    var dayMod = LockTime % 1440;
                    var day = (LockTime - dayMod) / 1440;
                    var minute = dayMod % 60;
                    var hour = (dayMod - minute) / 60;
                    return string.Format("{0} Ngày {1} Giờ {2} Phút", day, hour, minute);
                }
                else
                {
                    return "";
                }
            }  
        }
        public List<string> LstRoleName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeactive { get; set; }
        public bool IsEditable { get; set; }
    }
}

CheckinV02/Controllers/CommonController.cs
using CheckinV02.BL;
using CheckinV02.Common;
using CheckinV02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CheckinV02.Controllers
{
    public class CommonController : Controller
    {
        ICurrUserBL CurrentUser;
        public CommonController(ICurrUserBL currentUser)
        {
            this.CurrentUser = currentUser;
        }

        // GET: Common
        public ActionResult Header()
        {
            var currUser = CurrentUser.GetCurrentUser();

            var userHeaderViewer = new UserHeaderViewModel();
            // Check user management permission
            if (currUser.HasRole(Permission.Admin.GetHashCode(), Permission.Manager.GetHashCode()))
            {
                userHeaderViewer.IsUserManager = true;
            }
            // Check invitee management permission
            if (currUser.HasRole(Permission.Admin.GetHashCode(), Permission.Manager.GetHashCode(), Permission.InviteeManager.GetHashCode()))
            {
                userHeaderViewer.IsInviteeManager = true;
            }
            // Check event management permission
            if (currUser.HasRole(Permission.Admin.GetHashCode(), Permission.Manager.GetHashCode()))
            {
                userHeaderViewer.IsEventManager = true;
            }

            return View(userHeaderViewer);
        }

        public ActionResult Paging(PagerModel pager)
        {
            return View(pager);
        }
    }
}

CheckinV02/Controllers/UserController.cs
using CheckinV02.BL;
using CheckinV02.Common;
using CheckinV02.Models;
using Libs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace CheckinV02.Controllers
{
    public class UserController : Controller
    {
        ICurrUserBL CurrentUser;
        IUserBL UserBL;
        public UserController(ICurrUserBL currentUser, IUserBL userBL)
        {
            this.CurrentUser = currentUser;
            this.UserBL = userBL;
        }
        public ActionResult Index()
        {
            var currUser = CurrentUser.GetCurrentUser();
            if (currUser.HasRole(Permission.Manager.GetHashCode(), Permission.Admin.GetHashCode()))
            {
                var model = new UserIndexModel();
                // Check add user permission
                if (currUser.HasRole(Permission.Admin.GetHashCode()))
                {
                    model.IsAddNewUser = true;
                }
                return View(model);
            }
            else
            {
                return View("~/Views/Common/ErrorManual.cshtml", null, "Bạn không có quyền thực hiện chức năng này");
            }
        }

        public ActionResult Search( UserIndexModel model)
        {
            Thread.Sleep(2000);
            var currUser = CurrentUser.GetCurrentUser();
            if (!currUser.HasRole(Permission.Admin.GetHashCode(), Permission.Manager.GetHashCode()))
            {
                return View("~/Views/Common/ErrorManual.cshtml", null, "Bạn không có quyền thực hiện chức năng này");
            }
            var totalRecord = 0;
            var lstUser = UserBL.Search(currUser, model,out totalRecord);
            var pager = new PagerModel { CurrentPage = model.PageIndex, PageSize = model.PageSize, TotalItem = totalRecord };
            ViewBag.Pager = pager;
            return View(lstUser);
        }

        public ActionResult AddNew()
        {
            Thread.Sleep(2000);
            var model = new UserUpdateModel();
            return View(model);
        }

        public JsonResult AddNewAction(UserUpdateModel model)
        {
            Thread.Sleep(2000);
            var response = new Response();
            var currUser = CurrentUser.GetCurrentUser();
            if(!currUser.HasRole(Permission.Admin.GetHashCode()))
            {
                response.Code = SystemCode.NotPermitted;
                response.Message = "Bạn không có quyền thực thi chức năng này !";
                return Json(response, JsonRequestBehavior.DenyGet);
            }
            // Bổ sung thông tin người dùng mới
            response= UserBL.AddNewUser(model);
            if(response.Code == SystemCode.Success)
            {
                response.Message = "Bạn đã thêm mới tài khoản thành công !";
            }
            return Json(response, JsonRequestBehavior.DenyGet);
        }
    }
}

CheckinV02/Views/User/AddNew.cshtml
@using CheckinV02.Models
@model UserUpdateModel
@{
    Layout = null;
}
<div id="frmAddNewUser" style="margin-top:25px;">
    <div class="form-group col-md-12">
        <label for="txtUsername" class="control-label" >Tên đăng nhập <span style="color:Red;">*</span></label>
        <div class="input-group">
            <input id="txtUsername" class="form-control text-input" name="username" type="text" />
        </div>
        <div class="show-message"></div>
    </div>
    <div class="form-group col-md-12">
        <label for="txtPassword" class="control-label">Mật khẩu <span style="color:Red;">*</span></label>
        <div class="input-group">
            <input id="txtPassword" class="form-control text-input" name="password" type="password" />
        </div>
        <div class="show-message"></div>
    </div>
    <div class="form-group col-md-12">
        <label for="txtReTypePassword" class="control-label">Nhập lại mật khẩu <span style="color:Red;">*</span></label>
        <div class="input-group">
            <input id="txtReTypePassword" class="form-control text-input" name="password" type="password" />
        </div>
        <div class="show-message"></div>
    </div>
    <div class="form-group col-md-12">
        <label for="txtReTypePassword" class="control-label">Vai trò</label><br />
        <div class='input-group'>
            @foreach (var item in Model.AllRole)
            {
                <input type="checkbox" name="grRole" renum="@item.Key" />  @item.Value <br />
            }
        </div>
        <div class="show-message"></div>
    </div>
    <hr />
    <div class="actions col-md-12">
        <button id="btnSave" type="button" class="btn btn-primary"><i class="icon-save"></i>&nbsp;Lưu</button>
        <button id="btnCancel" type="button" class="btn btn-primary"><i class="icon-refresh"></i>&nbsp;Reset</button>
        <button id="btnClose" type="button" class="btn btn-primary"><i class="icon-remove"></i>&nbsp;Đóng</button>
    </div>
</div>

CheckinV02/Views/User/Index.cshtml
@using CheckinV02.Models
@model UserIndexModel
@{
    Layout = null;
}
<h1 style="padding-left:15px;">Quản lý tài khoản</h1>
<div class="panel panel-search" id="frmSearchUser">
    <div class="panel-heading"><i class="icon-cogs"></i> &nbsp; Tìm kiếm thông tin người dùng</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-9">
                <div class="input-group">
                    <input id="txtSearchText" name="SearchText" type="text" class="form-control" placeholder="--Thông tin tìm kiếm--" />
                </div>
            </div>
            <div class="col-md-3">
                <button id="btnSearch" style="margin-left:3px;" class="btn btn-success" type="button"><i class="icon-search"></i>&nbsp;Tìm kiếm</button>
                @if (Model.IsAddNewUser)
                {
                    <button id="btnAddNew" class="btn btn-success" type="button"><i class="icon-plus"></i>&nbsp;Thêm mới</button>
                }
            </div>
        </div>
    </div>
</div>
<div class="panel panel-result" id="SearchUser">
    <div class="panel-heading"><i class="icon-cogs"></i> &nbsp; Danh sách người dùng</div>
    <div class="panel-body">
    </div>
</div>
<div class="panel panel-action hide" id="AddNewUser">
    <div class="panel-heading"><i class="icon-cogs"></i> &nbsp; Thêm / sửa người dùng</div>
    <div class="panel-body">
    </div>
</div>
<div class="panel panel-action hide" id="LockTemporaryUser">
    <div class="panel-heading"><i class="icon-cogs"></i> &nbsp; Khóa tài khoản tạm thời</div>
    <div class="panel-body">
    </div>
</div>
<script type="text/javascript">
    user_index.init();
</script>

CheckinV02/Views/User/Search.cshtml
@using CheckinV02.Models
@model List<UserViewModel>
@{
    var count = 0;
    Layout = null;
    var pager = (PagerModel)ViewBag.Pager;
    pager.ActionScript = "user_index.search";
}

<table id="tablUsers" class="table-striped table-bordered  col-md-12">
    <thead>
        <tr>
            <th class="col-md-1">STT</th>
            <th class="col-md-2">Tên tài khoản</th>
            <th class="col-md-2">Trạng thái</th>
            <th class="col-md-2">Ngày bắt đầu khóa</th>
            <th class="col-md-2">Thời gian khóa</th>
            <th class="col-md-2">Vai trò</th>
            <th class="col-md-1"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            count++;
            <tr>
                <td style="padding-left:3px;">@count</td>
                <td style="padding-left:3px;">@item.UserName</td>
                <td style="padding-left:3px;">
                    @if (item.Status == 1)
                    {
                        <span class="label  label-success">Hoạt động</span>
                    }
                    else
                    {
                        <span class="label  label-danger">Chưa hoạt động</span>
                    }
                </td>
                <td>
                    @if (item.LockedStartDate != null)
                    {
                        <span>@item.LockedStartDate.Value.ToString("dd/MM/yyyy")  <b>@item.LockedStartDate.Value.ToString("HH:mm:ss")</b> </span>
                    }
                </td>
                <td>
                    @item.LockTimeHtml
                </td>
                <td style="padding-left:3px;">
                    @foreach (var roleName in item.LstRoleName)
                    {
                        <span> @roleName </span> <br />
                    }
                </td>
                <td style="padding-left:3px;">
                    <div class="dropdown">
                        <button class="btn btn-primary small dropdown-toggle" style="font-size:11px !important;line-height:13px;padding:4px 10px;" type="button" data-toggle="dropdown">
                            <i class="icon-cog"></i>&nbsp;Quản lý
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            @if (item.IsEditable)
                            {
                                <li><a name="btnEdit" uname="@item.UserName" href="javascript:void(0);"><i class="icon-edit"></i>&nbsp;Sửa</a></li>
                            }
                            @if (item.IsDeactive )
                            {
                                <li><a name="btnDeActive" uname="@item.UserName" href="javascript:void(0);"><i class="icon-lock"></i>&nbsp;Bỏ kích hoạt</a></li>
                            }
                            @if (item.IsActive)
                            {
                                <li><a name="btnActive" uname="@item.UserName" href="javascript:void(0);"><i class="icon-unlock"></i>&nbsp;Kích hoạt</a></li>
                            }
                            @if (item.LockedStartDate != null)
                            {
                                <li><a name="btnUnLockTemp" uname="@item.UserName" href="javascript:void(0);"><i class="icon-unlock"></i>&nbsp;Bỏ khóa tạm thời</a></li>
                            }
                            else
                            {
                                <li><a name="btnLockTemp" uname="@item.UserName" href="javascript:void(0);"><i class="icon-lock"></i>&nbsp;Khóa tạm thời</a></li>
                            }
                        </ul>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.Action("Paging", "Common", new { pager = ViewBag.Pager })